version: "3.9"

services:
  event-microservice:
    build: .
    container_name: event-microservice
    hostname: event-microservice
    ports:
      - "4444:8080"
    environment:
      USERNAME_DATABASE: ${USERNAME_DATABASE}
      PASSWORD_DATABASE: ${PASSWORD_DATABASE}
      URL_EUREKA: ${URL_EUREKA}
      IP_HOST: ${IP_HOST}
      PORT_HOST: ${PORT_HOST}
      URL_DATABASE: ${URL_DATABASE}

  
  event-microservice-qa:
    build: .
    container_name: event-microservice-qa
    hostname: event-microservice-qa
    ports:
      - "24444:8080"
    environment:
      USERNAME_DATABASE: ${USERNAME_DATABASE}
      PASSWORD_DATABASE: ${PASSWORD_DATABASE_QA}
      URL_EUREKA: ${URL_EUREKA_QA}
      IP_HOST: ${IP_HOST}
      PORT_HOST: ${PORT_HOST_QA}
      URL_DATABASE: ${URL_DATABASE_QA}
