spring:
  datasource:
    url: "jdbc:mysql://${URL_DATABASE}/event"
    username: ${USERNAME_DATABASE}
    password: ${PASSWORD_DATABASE}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: event-microservice

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${URL_EUREKA}/eureka"
  instance:
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "9090"
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator

    prefer-ip-address: true
    ip-address: "${IP_HOST}"
    nonSecurePort: "${PORT_HOST}"

management:
  endpoints:
    web:
      exposure:
        include: "*"